// ============================================================
//  Teensy_lib/src/BotConnect.cpp
//  BL-compatible library for Teensy 4.0
// ============================================================

#include "BotConnect.h"
#include <string.h>
#include <stdio.h>
#include <stdlib.h>

BotConnect BC;

void BotConnect::begin(HardwareSerial &serial, uint8_t satId) {
    _serial = &serial;
    _satId  = satId;
    _rxIdx  = 0;
}

// ─── Main loop ───────────────────────────────────────────────
void BotConnect::process() {
    if (!_serial) return;

    while (_serial->available()) {
        char c = (char)_serial->read();
        if (c == '\n' || c == '\r') {
            if (_rxIdx > 0) {
                _rxBuf[_rxIdx] = '\0';
                _parseLine(_rxBuf);
                _rxIdx = 0;
            }
        } else {
            // Add character only if there's space, discard line on overflow
            if (_rxIdx < (int)(sizeof(_rxBuf) - 1)) {
                _rxBuf[_rxIdx++] = c;
            } else {
                // Buffer overflow - discard the entire line
                _rxIdx = 0;
            }
        }
    }
}

// ─── Line parser ─────────────────────────────────────────────
// Commands from ESP satellite follow the patterns generated by
// CommandParser::_buildXxxCmd() in ESP_Satellite firmware.
//
// Examples:
//   V200A-45SW3BTN0START1    -> control
//   M3                        -> mode
//   CAL_IR_MAX                -> calibrate
//
// P2P messages from peer robot:
//   Any line that is not a command or DBG: prefixed line
//   is treated as a P2P message from the peer robot
void BotConnect::_parseLine(const char *line) {
    if (!line || line[0] == '\0') return;

    // Control command: starts with 'V'
    // Format: V<speed>A<angle>SW<sw>BTN<btn>START<start>
    if (line[0] == 'V') {
        int speed = 0, angle = 0, sw = 0, btn = 0, start = 0;
        int parsed = sscanf(line, "V%dA%dSW%dBTN%dSTART%d",
                            &speed, &angle, &sw, &btn, &start);
        if (parsed == 5 && _onCtrl) {
            _onCtrl((int16_t)speed, (int16_t)angle,
                    (uint8_t)sw, (uint8_t)btn, (uint8_t)start);
        }
        return;
    }

    // Mode command: M<n>
    if (line[0] == 'M' && line[1] >= '1' && line[1] <= '5') {
        uint8_t modeId = (uint8_t)(line[1] - '0');
        if (_onMode) _onMode(modeId);
        return;
    }

    // Calibrate: CAL_*
    if (strncmp(line, "CAL_", 4) == 0) {
        if (_onCal) _onCal(line);  // Pass full "CAL_IR_MAX" etc.
        return;
    }

    // ACK messages: ACK<seq>:<status>
    // These are internal protocol messages, not dispatched to user
    if (strncmp(line, "ACK", 3) == 0) {
        // Internal ACK handling (future use)
        return;
    }

    // P2P message from peer robot
    // Any line that doesn't match the above patterns is a P2P message
    if (_onP2P) {
        _onP2P(line);
        return;
    }

    if (_debugEnabled) {
        char dbg[64];
        snprintf(dbg, sizeof(dbg), "[BC] unknown cmd: %s", line);
        // Can't use Serial inside lib without knowing which port
        // Caller can log via custom handler if needed
        (void)dbg;
    }
}

// ─── Telemetry send helpers ───────────────────────────────────
// Wire format expected by CommandParser::uartLineToFrame():
//   DBG:name=value\n   (unified prefix as of protocol v1)
// The satellite firmware automatically tags telemetry with the correct SAT ID

void BotConnect::sendTelemetryInt(const char *name, int32_t value) {
    if (!_serial) return;
    char buf[64];
    snprintf(buf, sizeof(buf), "DBG:%s=%ld\n", name, (long)value);
    _sendLine(buf);
}

void BotConnect::sendTelemetryFloat(const char *name, float value) {
    if (!_serial) return;
    char buf[64];
    snprintf(buf, sizeof(buf), "DBG:%s=%.4f\n", name, value);
    _sendLine(buf);
}

void BotConnect::sendTelemetryBool(const char *name, bool value) {
    if (!_serial) return;
    char buf[64];
    snprintf(buf, sizeof(buf), "DBG:%s=%d\n", name, value ? 1 : 0);
    _sendLine(buf);
}

void BotConnect::sendTelemetryString(const char *name, const char *value) {
    if (!_serial) return;
    char buf[64];
    snprintf(buf, sizeof(buf), "DBG:%s=%s\n", name, value);
    _sendLine(buf);
}

void BotConnect::sendAck(uint8_t seq, uint8_t status) {
    if (!_serial) return;
    char buf[32];
    snprintf(buf, sizeof(buf), "ACK%u:%u\n", seq, status);
    _sendLine(buf);
}

void BotConnect::_sendLine(const char *line) {
    if (_serial) _serial->print(line);
}
