#pragma once
// ============================================================
//  Teensy_lib/src/BotConnect.h
//  BL-compatible library for Teensy 4.0
//  Handles UART bridge communication with ESP_Satellite
// ============================================================

#include <Arduino.h>

// ── Command constants ─────────────────────────────────────────
// These match the command strings generated by CommandParser
#define CMD_CAL_IR_MAX    "CAL_IR_MAX"
#define CMD_CAL_IR_MIN    "CAL_IR_MIN"
#define CMD_CAL_LINE_MAX  "CAL_LINE_MAX"
#define CMD_CAL_LINE_MIN  "CAL_LINE_MIN"
#define CMD_CAL_BNO       "CAL_BNO"

// ── Telemetry value types ─────────────────────────────────────
#define TELEM_INT    0
#define TELEM_FLOAT  1
#define TELEM_BOOL   2
#define TELEM_STRING 3

// ── Callback signatures ───────────────────────────────────────
typedef void (*OnModeCb)(uint8_t modeId);
typedef void (*OnCalibrateCb)(const char *calCmd);
typedef void (*OnControlCb)(int16_t speed, int16_t angle,
                            uint8_t switches, uint8_t buttons,
                            uint8_t start);

class BotConnect {
public:
    // ── Initialisation ─────────────────────────────────────────
    // serial: the HardwareSerial connected to the ESP satellite
    // satId:  1 or 2 – determines DBG prefix (DBG1: or DBG2:)
    void begin(HardwareSerial &serial, uint8_t satId = 1);

    // ── Main loop – must be called in loop() ──────────────────
    void process();

    // ── Register command callbacks ────────────────────────────
    void onMode(OnModeCb cb)         { _onMode = cb; }
    void onCalibrate(OnCalibrateCb cb) { _onCal = cb; }
    void onControl(OnControlCb cb)   { _onCtrl = cb; }

    // ── Telemetry helpers ─────────────────────────────────────
    // Send a named integer stream value
    void sendTelemetryInt(const char *name, int32_t value);
    // Send a named float stream value
    void sendTelemetryFloat(const char *name, float value);
    // Send a named bool stream value
    void sendTelemetryBool(const char *name, bool value);
    // Send a named string stream value
    void sendTelemetryString(const char *name, const char *value);

    // ── ACK generation ────────────────────────────────────────
    // Send positive ACK for last received command (auto-called internally)
    void sendAck(uint8_t seq, uint8_t status = 0);

    // ── Debug output ──────────────────────────────────────────
    void setDebugEnabled(bool en) { _debugEnabled = en; }

private:
    HardwareSerial *_serial = nullptr;
    uint8_t         _satId  = 1;
    bool            _debugEnabled = true;

    char    _rxBuf[512];
    int     _rxIdx = 0;

    OnModeCb      _onMode = nullptr;
    OnCalibrateCb _onCal  = nullptr;
    OnControlCb   _onCtrl = nullptr;

    void _parseLine(const char *line);
    void _sendLine(const char *line);
};

// Global instance (compatible with BL.h usage pattern)
extern BotConnect BC;
